### ISSUE TITLE
[BUG] The game crashes when a battle starts 

### ISSUE THREAD

**Issue by dep1engenharia** [lanedirt/OGameX#403] opened 2024-10-19 12:58 UTC
**Describe the bug**
Hi, :)

The game crashes when I attack another planet and the battle begins. After sending 700,000 cruisers to attack, the browser screen turns white as soon as they reach the target planet.

Then, to play again, I have to delete everything, including the database.

I have already tried a clean install and deleted all old containers, images, and volumes. The issue occurs in both DEV and PROD versions.

**To Reproduce**
1. Go to the game
2. Attack another planet by example with 5000 spionage probs
3. wait for the impact

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/942e7493-6769-4608-83d8-72093c3a40db)

**Additional context**
The game was working very fine to me, untill I update it yesterday.

BIG thank you for all the developers!

**Comment by lanedirt** [comment] 2024-10-19 23:17
Hi @dep1engenharia,

Thank you for your bug report. 👍  I attempted to reproduce the issue locally, but on my end, a battle with 5k espionage probes runs without any errors.

Afterwards I tested it with 700K cruisers and that indeed also crashes the game for me. So I'm suspecting this error has something to do with very large amounts of fleets. Up until now I only tested the battle system with a few hundred units max. But higher amounts should of course also work.

So thanks again for reporting this issue, I'll try to look into it in the coming days! 😄

**Comment by dep1engenharia** [comment] 2024-10-20 00:08
Hi @lanedirt 

The game is starting to get bigger and more complex 😅🤣

But you're doing an excellent job 👏 

Keep pushing. 🙏

Thank you !!

**Comment by lanedirt** [comment] 2024-10-20 17:57
Hi @dep1engenharia,

I have investigated the issue, and it was caused by an out-of-memory exception. The PHP process was configured with a maximum memory limit of 128MB. I have increased this to 1GB, and now a battle with around 900K units is successfully processed. However, processing a battle with these 900K+ units takes around 60 seconds, which is too slow for OGame purposes.

Therefore, I have created a new issue (#406) to cover work on improving the BattleEngine logic for larger fleet numbers.

Regarding the white page error issue: if you update your local server with the latest main branch, this error should now be resolved and the battle report should get generated without an error. Can you check if this indeed fixes it for you?

**Comment by dep1engenharia** [comment] 2024-10-20 20:55
Hi @lanedirt,

I don't believe the memory limit is the only issue. The first time I encountered this problem, I attacked a planet with fewer than 10 probes to generate debris before launching the main attack.

The second time, I used 5000 probes, and now I replicated the attack with 700,000 cruisers, which caused my browser to go completely white.

I also noticed that I can only send recyclers when there's already debris in the galaxy. Additionally, I can only send them from the galaxy view, not the same way I launch an attack. Instead of launching an attack, I choose the recycle option in the Fleet Dispatch menu. This is very useful because I attack and recycle with a 1-second difference to prevent anyone from stealing my debris. That was the behavior in the original game, though I’m not sure if it has changed since I haven’t played in years.

Obs:
Tested in PROD env

Overall, the issue persists.

Thank you 👍

**Comment by lanedirt** [comment] 2024-10-21 09:07
Hi @dep1engenharia,

Thanks for your detailed feedback!

> I don't believe the memory limit is the only issue. The first time I encountered this problem, I attacked a planet with fewer than 10 probes to generate debris before launching the main attack.
> 
> The second time, I used 5000 probes, and now I replicated the attack with 700,000 cruisers, which caused my browser to go completely white.

I was only able to replicate it with a large fleet size, but with smaller amounts, it didn’t seem to occur. If you have an example where this happens consistently for you, it would be very helpful. I'll reopen this issue awaiting your reply.

> I also noticed that I can only send recyclers when there's already debris in the galaxy. Additionally, I can only send them from the galaxy view, not the same way I launch an attack. Instead of launching an attack, I choose the recycle option in the Fleet Dispatch menu. This is very useful because I attack and recycle with a 1-second difference to prevent anyone from stealing my debris. That was the behavior in the original game, though I’m not sure if it has changed since I haven’t played in years.

Regarding sending recyclers from the fleet dispatch menu, could you confirm if you’re selecting the “Debris field” and not “Planet,” which is selected by default? See the screenshot below. If you’re still experiencing issues with the recycler logic, feel free to open a new issue so we can dive deeper into it there.

<img width="667" alt="Screenshot 2024-10-21 at 10 59 31" src="https://github.com/user-attachments/assets/b43d761f-da13-44ec-918a-436d453aff0f">

Thanks again for your help and taking the time to report these issues. It's very helpful! 👍

**Comment by dep1engenharia** [comment] 2024-10-21 19:15
Hello @lanedirt 

Your're right about the Debris Field.

I did that way and it works. Tks!

About the crashes when a battle starts... you can check this video.

https://www.youtube.com/watch?v=0s7NWiV-db8

As for the 700,000 cruisers, that was my fleet when I was an active player.

Thank you.
👍

**Comment by lanedirt** [comment] 2024-10-21 20:15
Hi @dep1engenharia,

Thank you for the YouTube video. Based on the footer of the game client, I noticed that you're currently on the 0.8.0 (stable) branch. Is that correct? The fix I committed in PR #404 is currently only available on the `main` git branch. If you switch from the 0.8.0 tag to the main branch, the white screen error should disappear.

Could you try this?

**Comment by dep1engenharia** [comment] 2024-10-21 20:56
Hi @lanedirt 

Ah okok. I will test it tomorrow and I will keep you posted.

Thank you.

**Comment by dep1engenharia** [comment] 2024-10-26 11:49
Hi @lanedirt 
Sorry for the delay.. all good.

You can close the issue. 

Thank you 🥂🙏

Have a nice weekend.

**Comment by lanedirt** [comment] 2024-10-26 15:57
Good to hear! Closing issue.

**Closed by lanedirt** 2024-10-26 15:57 UTC
Labels: bug
